# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FQbGsbfzcRrHSd8Vi18yEVoMK9n5ZU8
"""

import json
import os
import requests
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import pytz
import getpass
import sys


# ────────────────────────────────────────────────
# Константы
# ────────────────────────────────────────────────

LOG_FILE          = "eve.json"
DEMO_LOG_FILE     = "demo.eve.json"
REPORT_CSV        = "report.csv"
REPORT_JSON       = "report.json"
GRAPH_FILE        = "graph.png"

ALERT_THRESHOLD   = 5

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID   = os.getenv("TELEGRAM_CHAT_ID", "")


def create_demo_logs():
    """Создаёт демонстрационный файл логов в формате Suricata eve.json."""
    demo_events = [
        {"timestamp": "2026-03-11T10:15:22", "event_type": "alert", "src_ip": "185.220.101.12", "alert": {"severity": 3, "signature": "ET MALWARE C2 Beacon"}},
        {"timestamp": "2026-03-11T10:15:25", "event_type": "alert", "src_ip": "185.220.101.12", "alert": {"severity": 3, "signature": "ET MALWARE C2 Beacon"}},
        {"timestamp": "2026-03-11T10:15:28", "event_type": "alert", "src_ip": "185.220.101.12", "alert": {"severity": 3, "signature": "ET MALWARE C2 Beacon"}},
        {"timestamp": "2026-03-11T10:15:31", "event_type": "alert", "src_ip": "185.220.101.12", "alert": {"severity": 3, "signature": "ET MALWARE C2 Beacon"}},
        {"timestamp": "2026-03-11T10:15:34", "event_type": "alert", "src_ip": "185.220.101.12", "alert": {"severity": 3, "signature": "ET MALWARE C2 Beacon"}},
        {"timestamp": "2026-03-11T10:16:10", "event_type": "alert", "src_ip": "45.32.123.45",  "alert": {"severity": 2, "signature": "ET SCAN Nmap"}},
        {"timestamp": "2026-03-11T10:16:12", "event_type": "alert", "src_ip": "45.32.123.45",  "alert": {"severity": 2, "signature": "ET SCAN Nmap"}},
        {"timestamp": "2026-03-11T10:17:05", "event_type": "alert", "src_ip": "172.67.89.101", "alert": {"severity": 1, "signature": "Suspicious DNS Query"}},
    ]

    with open(DEMO_LOG_FILE, "w", encoding="utf-8") as f:
        for event in demo_events:
            f.write(json.dumps(event, ensure_ascii=False) + "\n")


def load_alerts():
    """Загружает события alert из eve.json или создаёт демонстрационные данные."""
    if os.path.exists(LOG_FILE):
        print(f"Используется лог-файл: {LOG_FILE}")
        path = LOG_FILE
    else:
        print(f"Файл {LOG_FILE} не найден.")
        answer = input("Запустить в демонстрационном режиме? (да/нет): ").strip().lower()

        if answer not in ("да", "д", "y", "yes"):
            print("Работа завершена.")
            sys.exit(0)

        # При положительном ответе создаём демо-лог
        create_demo_logs()
        path = DEMO_LOG_FILE
        print(f"Демонстрационный режим: {DEMO_LOG_FILE}")

    events = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
                if event.get("event_type") == "alert":
                    src_ip = event.get("src_ip")
                    alert = event.get("alert", {})
                    events.append({
                        "src_ip": src_ip,
                        "severity": alert.get("severity"),
                        "signature": alert.get("signature", "—")
                    })
            except json.JSONDecodeError:
                continue

    df = pd.DataFrame(events)
    if df.empty:
        print("В файле нет событий типа alert")
    return df


def get_vt_api_key():
    """Возвращает ключ VirusTotal или пустую строку при пропуске."""
    key = os.getenv("VT_API_KEY")

    if key and key.strip():
        print(f"VirusTotal API-ключ найден (длина {len(key)} символов)")
        return key

    print("\nVirusTotal API-ключ не найден.")
    print("Введите ключ или нажмите Enter для работы без VirusTotal")
    key = getpass.getpass("VirusTotal API-ключ: ").strip()

    if key:
        print("Ключ принят")
    else:
        print("Продолжаем без VirusTotal")

    return key


def get_telegram_credentials():
    """Возвращает токен и chat_id Telegram или пустые строки."""
    token = os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHAT_ID")

    if token and chat_id and token.strip() and chat_id.strip():
        print(f"Telegram уведомления включены (чат {chat_id})")
        return token.strip(), chat_id.strip()

    print("\nTelegram-бот не настроен.")
    answer = input("Настроить уведомления в Telegram? (да/нет): ").strip().lower()
    if answer not in ("да", "д", "y", "yes"):
        return "", ""

    token = getpass.getpass("Telegram Bot Token: ").strip()
    chat_id = input("Telegram Chat ID (число): ").strip()

    if token and chat_id:
        print("Telegram подключён")
    else:
        print("Пропускаем Telegram")

    return token, chat_id


def check_vt_ip(ip, api_key):
    """Проверяет IP через VirusTotal API."""
    if not api_key:
        return "пропущено"

    url = f"https://www.virustotal.com/api/v3/ip_addresses/{ip}"
    headers = {"x-apikey": api_key}

    try:
        r = requests.get(url, headers=headers, timeout=10)
        if r.status_code == 200:
            stats = r.json()["data"]["attributes"]["last_analysis_stats"]
            malicious = stats.get("malicious", 0)
            return "malicious" if malicious > 0 else "clean"
        else:
            return f"err {r.status_code}"
    except Exception:
        return "err"


def send_telegram_alert(ip, count, vt_status, now):
    """Отправляет уведомление об угрозе в Telegram."""
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        return False

    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    text = f"""УГРОЗА ОБНАРУЖЕНА

IP: {ip}
Алертов: {count}
VirusTotal: {vt_status}
Время: {now:%Y-%m-%d %H:%M:%S} MSK

IP заблокирован (имитация)"""

    payload = {
        "chat_id": TELEGRAM_CHAT_ID,
        "text": text,
        "parse_mode": "HTML"
    }

    try:
        r = requests.post(url, data=payload, timeout=8)
        if r.status_code == 200:
            return True
        else:
            print(f"Telegram ошибка: {r.status_code}")
            return False
    except Exception as e:
        print(f"Telegram исключение: {e}")
        return False


def main():
    msk = pytz.timezone("Europe/Moscow")
    now = datetime.now(msk)
    print(f"\nАнализ угроз — {now:%Y-%m-%d %H:%M:%S} MSK")
    print("═" * 70)

    vt_key = get_vt_api_key()
    global TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID
    TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID = get_telegram_credentials()

    df = load_alerts()
    if df.empty:
        print("Нет данных для анализа")
        return

    agg = df.groupby("src_ip").size().reset_index(name="alert_count")
    agg = agg.sort_values("alert_count", ascending=False)

    results = []

    for _, row in agg.iterrows():
        ip = row["src_ip"]
        cnt = int(row["alert_count"])

        vt = check_vt_ip(ip, vt_key)

        threat = (cnt >= ALERT_THRESHOLD) or (vt == "malicious")

        print(f"  {ip:16}   алертов: {cnt:3}   VT: {vt:10}   {'УГРОЗА' if threat else 'нормально'}")

        if threat:
            print(f"     → имитация блокировки IP {ip}")
            if send_telegram_alert(ip, cnt, vt, now):
                print("     → уведомление отправлено в Telegram")
            else:
                print("     → Telegram не настроен / ошибка отправки")

        results.append({
            "ip": ip,
            "alert_count": cnt,
            "vt_status": vt,
            "threat": "YES" if threat else "нет"
        })

    df_out = pd.DataFrame(results)
    df_out.to_csv(REPORT_CSV, index=False, encoding="utf-8-sig")
    df_out.to_json(REPORT_JSON, orient="records", force_ascii=False, indent=2)

    print(f"\nСохранено:")
    print(f"  • {REPORT_CSV}")
    print(f"  • {REPORT_JSON}")

    if not df_out.empty:
        plt.figure(figsize=(10, 5))
        top = df_out.head(10)
        colors = ["#c62828" if t == "YES" else "#ff9800" for t in top["threat"]]

        plt.bar(top["ip"], top["alert_count"], color=colors)
        plt.title("Топ IP по количеству алертов")
        plt.ylabel("Количество алертов")
        plt.xlabel("IP")
        plt.xticks(rotation=45, ha="right")
        plt.tight_layout()
        plt.savefig(GRAPH_FILE, dpi=120, bbox_inches="tight")
        plt.close()

        print(f"График сохранён: {GRAPH_FILE}")

    print("═" * 70)


if __name__ == "__main__":
    main()
